### ISSUE TITLE
Project rationale?

### ISSUE THREAD

**Issue by aschrijver** [chentsulin/babel-plugin-transform-move-comments-to-top#3]
Why would you want to move comments to top?

**Comment by chentsulin** [comment]
`hubot-help` collect comments from top of files to generate help messages
https://github.com/hubot-scripts/hubot-help/blob/master/src/help.coffee

But babel will move those lines to the top:

``` js
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
```

So I use this module as another transform.

**Comment by aschrijver** [comment]
Thanks for clarification!
